### ISSUE TITLE
Document what Add-ons if any...

### ISSUE THREAD

**Issue by JasonSwindle** [joshix/caddybox#15]
Howdy,

From what I can figure, it looks like no add-ons are shipped in the CaddyBox docker image, but I do not see this documented either. Am I wrong?

Thanks,
Jason

**Comment by joshix** [comment]
That's correct, the caddy in caddybox is equivalent to downloading caddy from the caddyserver.com site with no "Features" selected. We don't ship any of the add-ons.

I can add a line to this effect in the README next time I push some changes.

Since the caddy here is statically linked and the environment doesn't include any libs or supporting linux distribution utilities, @abiosoft's caddy container built `FROM` alpine is usually the easier target for add-ons (like his git extension).

**Comment by joshix** [comment]
@JasonSwindle I'd welcome a PR to amend the README as you suggest, if you're interested. I completely forgot to mention that in my original response.

Otherwise I'll drop a note in sometime.

(Are you looking to use any particular addon?)
